---
- name: Copy MySQL secure script
  copy:
    src: mysql_secure_installation.sql
    dest: "/tmp/mysql_secure_installation.sql"
    mode: "0600"

- name: Secure MySQL Installation
  mysql_db:
    name: all
    state: import
    target: "/tmp/mysql_secure_installation.sql"
