---
# tasks file for kubernetes_worker

- name: Check if node is already joined the cluster
  uri:
    url: http://localhost:10248/healthz
  register: node_status
  ignore_errors: yes

- name: Join kubernetes cluster
  shell: kubeadm join {{ hostvars[groups.kubernetes_master.0].ansible_default_ipv4.address }}:6443 --token {{ hostvars['K8S_TOKEN_HOLDER']['token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}
  when: "'Connection refused' in node_status"