---
# tasks file for kubernetes_prepeare

- include_tasks: centos.yml
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
- include_tasks: ubuntu.yml
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "16")
